name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  audioplayers_linux: ^4.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.3+1
  youtube_explode_dart: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
